version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"  # Mapeia a porta 5000 do container para a porta 5000 da máquina host
    volumes:
      - ./data:/app/data  # Monta o diretório de dados para persistência
    environment:
      - FLASK_DEBUG=development  # Define o modo de desenvolvimento
